CREATE DATABASE IF NOT EXISTS blog_db;
USE blog_db;

CREATE TABLE POSTS (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT TEXT NOT NULL
);

CREATE TABLE TAGS (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE POST_TAGS (
	POST_ID INT,
    TAG_ID INT,
    PRIMARY KEY (POST_ID, TAG_ID),
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
    FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
);
