-- TABLE RELATED Queries-2

USE college;

--  UPDATE
UPDATE student SET grade = 'O' WHERE grade = 'A';

-- SET SQL_SAFE_UPDATES = 0;
-- SET SQL_SAFE_UPDATES = 1;
--USE THIS WHILE UPDATE AND DELETE OTHERWISE IT WON'T WORK OR USE FOLLOWING:
UPDATE student SET grade = 'B' WHERE ROLLNO IN (103, 106);

-- DELETE
DELETE FROM student WHERE marks<33;
